export enum Constants {
  SET_ITEMS = "SET_ITEMS",
  SET_PAGE = "SET_PAGE",
  SET_SEARCH_QUERY = "SET_SEARCH_QUERY",
  LOADING = "LOADING",
  SET_PAGES_COUNT = "SET_PAGES_COUNT",
  SET_SEARCH_HISTORY = "SET_SEARCH_HISTORY"
}
